name: Java CI

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Change this to your desired Java version

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Modify this command as per your build setup

      # Add steps for testing, deployment, etc. as needed
